# Configuration for https://github.com/openstax/staxly

# Configure which Project board (and column) to
# automatically add Issues and Pull Requests
project:
  type: "ORGANIZATION"
  number: 3
  new_issue_column:
    index: 0
    # name: "To do"
  new_pull_request_column:
    index: 1
    # name: "In progress"
