language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
script:
  # Verify the Unit tests do not differ
  - touch ./docbook-xsl/VERSION # xsltproc should fetch the XSL files from sourceforge
  - sudo apt-get install python-virtualenv docbook-xsl-ns
  - grunt -v diff

  # Verify the CSS files were compiled
  - grunt compile
  - ./tools/travis-check.sh
