coverage: true
prince: 'prince' # Path to princexml
testingDir: 'testing/'
books:
  # For each book you want to test, include the path to the complete ZIP file.

  # precalculus: '~/precalc-test-data'
  # sociology  : '~/col11407_1.7_complete'
  # economics  : '~/col11613_1.2_complete'
  # psychology : '~/col10018_1.7_complete'
  # statistics : '~/col11562_1.11_complete'
  # anatomy    : '~/col11496-1.6_complete'
  # biology    : '~/col11448_1.9_complete'
  # physics    : '~/col11406_1.7_complete'
