coverage: true # Generate CSS Coverage info
# Skip a task if the target file has already been generated
skipping:
  # Unless you change the CNXML or Docbook XSLT files you can probably
  # skip the PDF generation task

  # pdf:      true
  # pdfOnly:  false
  # coverage: false
  # bake:     false
  # preview:  false

prince: 'prince' # Path to princexml
testingDir: './testing'
books:
  # For each book you want to test, include the path to the UNZIPPED complete-zip file.

  # precalculus: '/some/path/to/precalc-test-data'
  # sociology  : '/some/path/to/col11407_1.7_complete'
  # economics  : '/some/path/to/col11613_1.2_complete'
  # psychology : '/some/path/to/col10018_1.7_complete'
  # statistics : '/some/path/to/col11562_1.11_complete'
  # anatomy    : '/some/path/to/col11496-1.6_complete'
  # biology    : '/some/path/to/col11448_1.9_complete'
  # physics    : '/some/path/to/col11406_1.7_complete'
