# prince: '/Users/phil/Downloads/prince-9.0-macosx/lib/prince/bin/prince'
prince: '/Users/phil/Downloads/prince-8.1r5-macosx/lib/prince/bin/prince'

testingDir: './tests-output'
books:
  precalculus: './tests/precalculus-book'
