#!/bin/bash

set -e
cd "$(dirname "$0")/.."

if [[ ! $1 ]]; then
  echo "Try adding --help to get more information"
  exit 1
else
  # Only activate the virtualenv if not already in one
  [[ -z "${VIRTUAL_ENV}" ]] && source ./venv/bin/activate

  # The XML Catalogs on OSX are not in the default directory because they are installed via homebrew
  if [[ $(which brew) ]]; then
    XML_CATALOG_FILES=$(brew --prefix)/etc/xml/catalog python collectiondbk2pdf.py $@
    exit $?
  else
    python collectiondbk2pdf.py $@
    exit $?
  fi

fi
