#!/bin/bash
cd "$(dirname "$0")/.."
source ./script/bootstrap || exit 111

odd_even="${1}"

if [[ ! ${odd_even} ]]; then
  _say "Note: This script takes an optional argument of 'odd' or 'even' to speed up the build process by using multiple cores"
  _say "You would need to open up 2 terminals and run this with the 'odd' or 'even' arg in each terminal"
fi

count=0
for config in "${BOOK_CONFIGS[@]}"; do
  read -r uuid collection_id style_name _ <<< "${config}"

  count=$((count+1))
  if [[ ${odd_even} == "even" && $((count%2)) != 0 ]]; then
    continue
  elif [[ ${odd_even} == "odd" && $((count%2)) == 0 ]]; then
    continue
  fi
  do_progress_quiet "Building the prepare file for ${style_name}" \
    ./script/build-pdf-prepare "${style_name}"
done
