#!/bin/bash

set -e
cd "$(dirname "$0")/.."

if [[ ! $1 ]]; then
  echo "Try adding --help to get more information"
  exit 1
else
  # Only activate the virtualenv if not already in one
  [[ -z "${VIRTUAL_ENV}" ]] && source ./venv/bin/activate

  python collectiondbk2pdf.py $1 $2 $3 $4 $5 $6 $7 $8 $9
  exit $?
fi
