#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

if [[ $1 ]]; then
  # Just compile 1 CSS file
  "$(npm bin)/grunt" "shell:compile:$1"
else
  # Compile all CSS files
  "$(npm bin)/grunt" compile
fi
