#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

if [[ ! $1 || ! -d "./data/$1/" ]]; then
  if [[ -d "./data/" && $(ls ./data/) ]]; then
    echo "A valid book name (directory in ./data/) needs to be specified. Valid options are:"
    ls ./data/
    exit 1
  else
    die "No source files in ./data/ exist. Please unzip a complete zip and name it something that matches one of the ccap-* names (without the ccap- prefix)"
  fi
else

  source_dir="./data/$1/"
  template_name="ccap-$1"
  pdf_name="./out/$1.pdf"
  temp_dir="./out/$1-temp/"

  # Check that the CSS file exists:
  if [[ ! -f "./css/${template_name}.css" ]]; then
    die "ERROR: ./css/${template_name}.css does not exist. The name provided is invalid."
  fi

  [[ -d "./out/" ]] || mkdir -p "./out/"
  [[ -d "${temp_dir}" ]] || mkdir -p "${temp_dir}"

  # Remove the PDF file if it already exists
  [[ -f "${pdf_name}" ]] && rm "${pdf_name}"

  do_progress_quiet "Compiling CSS file" \
    ./script/build-css "$1"

  do_progress_quiet "Building PDF from ${source_dir} (~5min. use DEBUG=true for progress)" \
    ./script/_build-pdf -v -d "${source_dir}" -s "${template_name}" -t "${temp_dir}" "$3" "${pdf_name}"

  if [[ $2 ]]; then
    xhtml_filename="$2"
    _say "Saving XHTML file to ${temp_dir}/${xhtml_filename}"
    try mv "${temp_dir}/collection.xhtml" "${temp_dir}/${xhtml_filename}"
  else
    xhtml_filename="collection.xhtml"
  fi
  xhtml_path="${temp_dir}/${xhtml_filename}"

  progress "Adding CSS reference into XHTML file for debugging"
  try sed -ir "s|</head>|<link rel=\"stylesheet\" type=\"text/css\" href=\"../../css/ccap-$1.css\" /></head>|" "${xhtml_path}"

  # _say "${c_green}Finished building PDF.${c_none} Opening now"
  # _say "You can also view the XHTML file used to generate the PDF at ${xhtml_path}"
  # if [[ $(which open) ]]; then
  #   open "${pdf_name}"
  # fi
  #
  if [[ $(which say) ]]; then
    # there is a say bash function so we need to use the bin version
    $(which say) "$1 PDF is done!"
  fi

fi
