#!/bin/bash -x
cd "$(dirname "$0")/.." || exit 111

dirs_to_remove=(
  node_modules
  venv
  build
  dist
  oer.exports.egg-info
  bin
  include
)

for dir_name in "${dirs_to_remove[@]}"
do
  if [[ -d "./${dir_name}/" ]]; then
    rm -rf "./${dir_name}/" || exit 111
  fi
done
