#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

book_name=${1}
diff_start_page=${2}
diff_end_page=${3}

# This is set to 1 when one of the diffs (PDF, XHTML, or XHTML+CSS) occurs
has_differences=0


check_file_exists() {
  [[ -f ${1} ]] || die "Expected file missing: '${1}' ${2}"
}

extracts_nums_rm_lead_zeros() {
  image_file_pg_num=$(echo ${image_file//[!0-9]/} | sed 's/^0*//' )
  #todo- figure out how to not use echo (rn w/out it, prints extra nums)
  #todo- make this more reuseable and replace ${image_file}
}

# diff_files() {
#   local type_label=${1}
#   local before_file=${2}
#   local after_file=${3}
#
#   # Check that the files exist
#   check_file_exists "${before_file}" "Try running ./script/diff-book-prepare {book_name}"
#   check_file_exists "${after_file}" "This is a bug that should be reported"
#
#   diff "${before_file}" "${after_file}" > /dev/null
#   local exit_status=$?
#   if [[ ${exit_status} != 0 ]]; then
#     has_differences=1
#     _say "${c_red}${type_label} mismatch found. Check '${before_file}' and '${after_file}'.${c_none}"
#   else
#     _say "${type_label} matches"
#   fi
# }

if [[ ! ${book_name} || ! -d "./data/${book_name}/" ]]; then
  if [[ -d "./data/" && $(ls ./data/) ]]; then
    echo "A valid book name (directory in ./data/) needs to be specified. Valid options are:"
    ls ./data
    exit 1
  else
    die "No source files in ./data/ exist. Please unzip a complete zip and name it something that matches one of the ccap-* names (without the ccap- prefix) OR use './script/fetch-book {book_name}' to do it for you"
  fi
else
  # Diff the PDF by comparing images of each page of the PDF

  pdf_file_before="./out/${book_name}.prepared.pdf"
  pdf_file_after="./out/${book_name}.pdf" # created in ./script/build-pdf

  xhtml_file_before="./out/${book_name}-temp/collection.prepared.xhtml" # created in ./script/diff-book-prepare
  xhtml_file_after="./out/${book_name}-temp/collection.xhtml" # created in ./script/build-pdf

  xhtml_file_pretty_before="./out/${book_name}-temp/collection.prepared.pretty.xhtml"

  # Check that all the prepared files exist
  check_file_exists "${pdf_file_before}" "Try running ./script/diff-book-prepare ${book_name} first"
  check_file_exists "${xhtml_file_pretty_before}" "Try running ./script/diff-book-prepare ${book_name} first"

  if [[ ! ${SKIP_PDF} ]]; then
    do_progress_quiet "Building PDF (and XHTML)" \
      ./script/build-pdf "${book_name}"
  else
    # Copy the collection.prepared.xhtml file if a file does not exist
    if [[ ! -f ${xhtml_file_after} ]]; then
      do_progress "Using the prepared XHTML file since PDF_SKIP=true and an existing XHTML file was not found. This usually is OK when only the CSS files changed"
      xhtml_file_after="${xhtml_file_before}"
    fi
  fi

  check_file_exists "${xhtml_file_after}" "Report this as a bug"

  [[ -d "./out/${book_name}-temp/after-pages/" ]] && try rm -rf "./out/${book_name}-temp/after-pages/"
  [[ -d "./out/${book_name}-temp/_after-pages/" ]] && try rm -rf "./out/${book_name}-temp/_after-pages/"

  # create the directory for the PDF images if it does not exist
  [[ -d "./out/${book_name}-temp/_after-pages/" ]] || try mkdir -p "./out/${book_name}-temp/_after-pages/"

  do_progress_quiet "Generating images for each page in the PDF" \
    convert "${pdf_file_after}" "./out/${book_name}-temp/_after-pages/page-%04d.png"

  # do_progress_quiet "Building XHTML with CSS 'baked in'" \
  #   "$(npm bin)/css-plus" --diffmodeclassnames --nostrict --timeout 0 --html "${xhtml_file_after}" --css "${css_path}" --output "${xhtml_and_css_file_after}"
  #
  # check_file_exists "${xhtml_and_css_file_after}" "Report this as a bug"
  #
  # # pretty-print the XHTML files so it is easier to diff
  # try xmllint --pretty 2 --output "${xhtml_file_pretty_after}"          "${xhtml_file_after}"
  # try xmllint --pretty 2 --output "${xhtml_and_css_file_pretty_after}"  "${xhtml_and_css_file_after}"
  #
  # # Diff the files and report when an error occurs
  # diff_files "PDF"        "${pdf_file_before}" "${pdf_file_after}"
  # diff_files "XHTML"      "${xhtml_and_css_file_pretty_before}" "${xhtml_and_css_file_pretty_after}"
  # diff_files "XHTML+CSS"  "${xhtml_file_pretty_before}" "${xhtml_file_pretty_after}"

  do_progress "Checking if all the images match"
  # Check that the images exist
  [[ -f "./out/${book_name}-temp/_prepared-pages/page-0000.png" ]] || die "Problem looping over the prepared pages. Try running ./script/diff-book-prepare ${book_name}"
  for image_file in $(cd "./out/${book_name}-temp/_prepared-pages" && ls ./*.png); do
    # Skip the 1st page because it contains a timestamp
    if [[ $(basename "${image_file}") == 'page-0000.png' ]]; then
      continue
    elif [[ ${diff_start_page} || ${diff_end_page} ]]; then
      extracts_nums_rm_lead_zeros
      if [[ ${image_file_pg_num} -lt ${diff_start_page} || ${image_file_pg_num} -gt ${diff_end_page} ]]; then
        continue
      fi
    fi
    # Compare the 2 images (from https://www.imagemagick.org/Usage/compare/#statistics)
    compare -metric AE "./out/${book_name}-temp/_prepared-pages/${image_file}" "./out/${book_name}-temp/_after-pages/${image_file}" null: 2> /dev/null
    exit_status=$?
    if [[ ${exit_status} != 0 ]]; then
      found_diffs+=("./out/${book_name}-temp/_prepared-pages/${image_file}")
    fi
  done

  if [[ "${found_diffs[@]}" ]]; then
    _say "Mismatches occured at:"
    # printf '%s\n' "${found_diffs[@]}"
    for each_diff in "${found_diffs[@]}"
    do
      _say "$each_diff"
    done
  fi
  if [[ ! "${found_diffs[@]}" ]]; then
    _say "${c_green}Yay! There were no differences between the PDFs, the XHTML, and the XHTML+CSS${c_none}"
  fi

  exit ${has_differences}
fi
