#!/bin/bash
cd "$(dirname "$0")/.."
source ./script/bootstrap || exit 1

book_name=${1}

# This is set to 1 when one of the diffs (PDF, XHTML, or XHTML+CSS) occurs
has_differences=0


check_file_exists() {
  [[ -f ${1} ]] || die "Expected file missing: "${1}" ${2}"
}

diff_files() {
  local type_label=${1}
  local before_file=${2}
  local after_file=${3}

  # Check that the files exist
  check_file_exists ${before_file} "Try running ./script/diff-book-prepare {book_name}"
  check_file_exists ${after_file} "This is a bug that should be reported"

  diff "${before_file}" "${after_file}" > /dev/null
  local exit_status=$?
  if [[ ${exit_status} != 0 ]]; then
    has_differences=1
    _say "${c_red}${type_label} mismatch found. Check '${before_file}' and '${after_file}'.${c_none}"
  else
    _say "${type_label} matches"
  fi
}

if [[ ! ${book_name} || ! -d "./data/${book_name}/" ]]; then
  if [[ -d "./data/" && $(ls ./data/) ]]; then
    echo "A valid book name (directory in ./data/) needs to be specified. Valid options are:"
    echo $(ls ./data/)
    exit 1
  else
    die "No source files in ./data/ exist. Please unzip a complete zip and name it something that matches one of the ccap-* names (without the ccap- prefix) OR use './script/fetch-book {book_name}' to do it for you"
  fi
else
  # Diff the PDF and the XHTML
  css_path="./css/ccap-${book_name}.css"

  pdf_file_before="./out/${book_name}.prepared.pdf"
  pdf_file_after="./out/${book_name}.pdf" # created in ./script/build-pdf

  xhtml_file_after="./out/${book_name}-temp/collection.xhtml" # created in ./script/build-pdf
  xhtml_and_css_file_after="./out/${book_name}-temp/collection.out.xhtml"

  xhtml_file_pretty_before="./out/${book_name}-temp/collection.prepared.pretty.xhtml"
  xhtml_file_pretty_after="./out/${book_name}-temp/collection.pretty.xhtml"

  xhtml_and_css_file_pretty_before="./out/${book_name}-temp/collection.prepared.out.pretty.xhtml"
  xhtml_and_css_file_pretty_after="./out/${book_name}-temp/collection.out.pretty.xhtml"

  # Check that all the prepared files exist
  check_file_exists "${pdf_file_before}" "Try running ./script/diff-book-prepare ${book_name} first"
  check_file_exists "${xhtml_file_pretty_before}" "Try running ./script/diff-book-prepare ${book_name} first"
  check_file_exists "${xhtml_and_css_file_pretty_before}" "Try running ./script/diff-book-prepare ${book_name} first"

  if [[ ! ${SKIP_PDF} ]]; then
    do_progress_quiet "Building PDF (and XHTML)" \
      ./script/build-pdf ${book_name}
  else
    # Copy the collection.prepared.xhtml file if a file does not exist
    if [[ ! -f ${xhtml_file_after} ]]; then
      do_progress "Using the prepared XHTML file since PDF_SKIP=true and an existing XHTML file was not found. This usually is OK when only the CSS files changed"
      xhtml_file_after="${xhtml_file_before}"
    fi
  fi

  check_file_exists "${xhtml_file_after}" "Report this as a bug"

  do_progress_quiet "Building XHTML with CSS 'baked in'" \
    "$(npm bin)/css-plus" --diffmodeclassnames --nostrict --timeout 0 --html "${xhtml_file_after}" --css "${css_path}" --output "${xhtml_and_css_file_after}"

  check_file_exists "${xhtml_and_css_file_after}" "Report this as a bug"

  # pretty-print the XHTML files so it is easier to diff
  try xmllint --pretty 2 --output "${xhtml_file_pretty_after}"          "${xhtml_file_after}"
  try xmllint --pretty 2 --output "${xhtml_and_css_file_pretty_after}"  "${xhtml_and_css_file_after}"

  # Diff the files and report when an error occurs
  diff_files "PDF"        "${pdf_file_before}" "${pdf_file_after}"
  diff_files "XHTML"      "${xhtml_and_css_file_pretty_before}" "${xhtml_and_css_file_pretty_after}"
  diff_files "XHTML+CSS"  "${xhtml_file_pretty_before}" "${xhtml_file_pretty_after}"

  if [[ ${has_differences} == 0 ]]; then
    _say "${c_green}Yay! There were no differences between the PDFs, the XHTML, and the XHTML+CSS${c_none}"
  fi

  exit ${has_differences}
fi
