#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

for config in "${BOOK_CONFIGS[@]}"; do
  read -r uuid _ style_name _ <<< "${config}"

  do_progress_quiet "Fetching ${style_name}" \
    ./script/fetch-book "${style_name}"
done
