#!/bin/bash
set -e

cd "$(dirname "$0")/.."

source ./script/bootstrap || exit 1

# JavaScript stuff
do_progress_quiet "Installing JavaScript Packages" \
  yarn --prefer-offline

# Python stuff
if [[ -f "./requirements.txt" || -f "./setup.py" ]]; then

  if [[ -n "${VIRTUAL_ENV}" ]]; then
    if [[ -f "./requirements.txt" ]]; then
      do_progress_quiet "Installing python packages" \
        pip install -r "./requirements.txt"
    else
      if [[ -f "./setup.py" ]]; then
        do_progress_quiet "Installing python packages from setup.py" \
          python setup.py install
      fi
    fi
  else
    echo "ERROR. Not in a virtualenv"
    exit 1
  fi
fi

if [[ ! -f ./lib/SaxonTransformWrapper.class ]]; then
  progress "Compiling XSLT2 Java classes"
  $(cd ./lib/ && javac -cp saxon9he.jar SaxonTransformWrapper.java)
fi

_say "${c_green}Successfully set up${c_none}"
