#!/bin/bash

set -e
cd "$(dirname "$0")/.."

# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
green_color="\033[0;32m"
yellow_color="\033[1;33m"
no_color='\033[0m'

say() {
  echo -e "$1"
}

progress() {
  say "${yellow_color}==> $1${no_color}"
}

progress 'Checking that we can fetch docbook-xsl from the XML catalog'
if [[ $(which brew) ]]; then
  declare -x XML_CATALOG_FILES=$(brew --prefix)/etc/xml/catalog
fi
xsltproc --catalogs --nonet ./docbook-xsl/xhtml-1_1/docbook.xsl ./test-ccap/m-anatomy/index_auto_generated.cnxml 2> /dev/null > /dev/null || exit 1


progress 'Building a test book "PDF"'
./script/build-pdf -d ./test-ccap/ -s ccap-physics -p ./script/_no-op-prince || exit 1

progress 'Compiling CSS files'
./script/build-css > /dev/null || exit 1

say "🎉 ${green_color}PASSED:${no_color} It seems all the tests passed 🎈"
