#!/bin/bash

cd "$(dirname "$0")/.."

# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
if [[ $(tput colors) -ge 8 ]]; then
  c_none=$(tput sgr0)
  # c_black=$(tput setaf 0)
  c_red=$(tput setaf 1)
  c_green=$(tput setaf 2)
  # c_brown=$(tput setaf 3)
  c_blue=$(tput setaf 4)
  c_purple=$(tput setaf 5)
  # c_cyan=$(tput setaf 6)
  # c_gray=$(tput setaf 7)
  c_dark=$(tput setaf 8)
  # c_lred=$(tput setaf 9)
  # c_lgreen=$(tput setaf 10)
  c_yellow=$(tput setaf 11)
  # c_lblue=$(tput setaf 12)
  # c_lpurple=$(tput setaf 13)
  c_lcyan=$(tput setaf 14)
  # c_white=$(tput setaf 15)
fi

say() { echo -e "$1"; }
progress() { say "${c_blue}==>${c_none} ${c_yellow}$1${c_none}"; }
# https://stackoverflow.com/a/25515370
yell() { >&2 say "$0: $*"; }
die() { yell "$1"; exit $2; }
try() { "$@" || die "${c_red}cannot run $*${c_none}" 112; }

do_progress() { progress "$1"; try $2 $3 $4 $5 $6 $7 $8 $9; }

# Alternative that outputs only when an error occurs
progress_quiet() { echo -e -n "${c_yellow}==>${c_none} $1 ... "; }
try_quiet() {
  _myout=$(mktemp -t 'stdout')
  _myerr=$(mktemp -t 'stderr')
  "$@" > ${_myout} 2> ${_myerr}
  substatus=$?
  if [[ ${substatus} != 0 ]]; then
    cat ${_myout}
    >&2 cat ${_myerr}
    rm ${_myout} ${_myerr}
    die "${c_red}ERROR: could not run $*${c_none}" ${substatus}
  else
    rm ${_myout} ${_myerr}
  fi
}
ok_quiet() { say "${c_green}OK${c_none}"; }
do_progress_quiet() {
  progress_quiet "$1"
  try_quiet $2 $3 $4 $5 $6 $7 $8 $9
  ok_quiet
}


if [[ $(which brew) ]]; then
  declare -x XML_CATALOG_FILES=$(brew --prefix)/etc/xml/catalog
fi
do_progress 'Checking that we can fetch docbook-xsl from the XML catalog' \
  xsltproc --catalogs --nonet --noout ./docbook-xsl/xhtml-1_1/docbook.xsl ./test-ccap/m-anatomy/index_auto_generated.cnxml

do_progress 'Building a test book "PDF"' \
  ./script/build-pdf -d ./test-ccap/ -s ccap-physics -p ./script/_no-op-prince

do_progress 'Compiling all CSS files' \
  ./script/build-css

say "${c_green}PASSED:${c_none} It seems all the tests passed 🎉"
