name: Check-CSS-Diff

on: push

jobs: 
  check-css-diff:
    name: Check PR for CSS changes
    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        node-version: [8.x, 10.x, 12.x]

    steps: 
      - name: checkout code 
        uses: actions/checkout@v2 

      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version}}

      - name: Install dependencies
        run: npm install

      - name: Compile CSS and check diff
        run: grunt compile
        run: ./tools/check-diff.sh

